services:
  - type: web
    name: employee-attendance-api
    env: node
    plan: free
    region: oregon
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: postgresql://israfil_hoque_t2cs_user:hvkekxgD4yDNiexIPcq51wGTK57plvOq@dpg-d4sqjv0gjchc73bk48tg-a/israfil_hoque_t2cs
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://employee-attendance-web.onrender.com
      - key: NODE_ENV
        value: production
      - key: DEFAULT_ADMIN_NAME
        value: Admin
      - key: DEFAULT_ADMIN_MOBILE
        value: "9999999999"
      - key: DEFAULT_ADMIN_EMPLOYEE_ID
        value: ADMIN001
      - key: DEFAULT_ADMIN_PASSWORD
        value: "01234"

  - type: static
    name: employee-attendance-web
    plan: free
    branch: main
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://employee-attendance-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
